---
title: "main_rmd"
output: html_document
date: "2023-02-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(torch)
library(progress)
source("utils_torch.R")
source("gain_torch_modified.R")
sim <- function(mr = 0.8){
  n  <- 5000
  n2 <- 5000 - 5000*mr
  
  beta <- c(1, 1, 1)
  e_U <- c(sqrt(3),sqrt(3))
  mx <- 0; sx <- 1; zrange <- 1; zprob <- .5
  
  simZ   <- rbinom(n, zrange, zprob)
  simX   <- (1-simZ)*rnorm(n, 0, 1) + simZ*rnorm(n, 0.5, 1)
  #error
  epsilon <- rnorm(n, 0, 1)
  #Y is added with epsilon
  simY    <- beta[1] + beta[2]*simX + beta[3]*simZ + epsilon
  #make X_star depends on it
  simX_tilde <- simX + rnorm(n, 0, e_U[1]*(simZ==0) + e_U[2]*(simZ==1))
  data_full <- data.frame(Y_tilde=simY, X_tilde=simX_tilde, Y=simY, X=simX, Z=simZ)
  ##### Designs
  ## SRS
  data <- data_full
  id_phase2 <- c(sample(n, n2))
  data$X[-id_phase2] <- NA
  data$R <- 0
  data$R[id_phase2] <- 1
  observed_resid <- data$X_tilde[id_phase2] - data$X[id_phase2]
  data$resid <- 0
  data$resid[id_phase2] <- observed_resid
  data$resid[-id_phase2] <- sample(observed_resid, n - n2, replace = T)
  return (list(data, data_full))
}
```

```{r}
#source("gain.R")
#source("utils.R")
#library(tensorflow)
#tf$constant("Hello Tensorflow!")
#x <- import("tensorflow.compat.v1") 
#x$disable_v2_behavior()
source("utils_torch.R")
source("gain_torch_modified_6.R")
library(torch)
library(progress)
output <- sim(mr = 0.9)
data <- output[[1]]
data_full <- output[[2]]
data$R <- NULL
ind <- is.na(data$X)
library(dplyr)
imp_list <- list()
coef <- sd <- NULL
for (i in 1:2){
  imp <- gain(data, vartype = c(1, 1, 1, 1, 0), 
              n = 10000, alpha = 10, hint_rate = 0.9, 
              batch_size = 128)
  mod <- lm(Y ~ X + Z, data = imp[ind, ])
  coef[i] <- coef(mod)[2]
  sd[i] <- sqrt(vcov(mod)[2, 2])
  
  imp$Z0 <- NULL
  imp$Z1 <- NULL
  imp_list[[i]] <- imp
}
coef
mean(coef)
sd
mean(sd) + (5 + 1) * var(coef) / 5
```

```{r}
#load("imp_list3.RData")

modfull <- lm(Y ~ X + Z, data = data_full)
summary(modfull)

modmis <- lm(Y ~ X + Z, data = data)
summary(modmis)
#data$R <- NULL
library(mixgb)
data$R <- NULL
plot_hist(imputation.list = imp_list, var.name = "X",
    original.data = data)
```


```{r}
data <- read.csv("Data/tryMis1One0.csv", header = F)
names(data) <- c("index", "X_tilde", "Y", "X", "Z", "resid")
```



```{r}
hyperimpute <- read.csv("hyperimpute_gain.csv", header = F)

names(hyperimpute) <- names(data)
mod <- lm(X ~ X_tilde + Z + Y, data = hyperimpute)
summary(mod)
modfull <- lm(X ~ X_tilde + Z + Y, data = data_full)
summary(modfull)

library(mixgb)
head(data)
plot_hist(imputation.list = imp_list, var.name = "X",
    original.data = data)

```


```{r}
load("SampleData_0001.RData")
library(survey)
library(data.table)
library(tidyverse)
data <- samp <- as.data.frame(samp) 
samp.solnas <- samp[(samp$solnas==T),]
lm.lsodi <- glm(c_ln_na_bio1 ~ c_age + c_bmi + c_ln_na_avg + high_chol + usborn + female + bkg_pr + bkg_o,
                data=samp.solnas)
samp$c_ln_na_calib <- as.matrix(predict(lm.lsodi, newdata=samp, type = 'response'))
samp <- samp %>% dplyr::select(-matches("true")) %>% dplyr::select(-matches("bio"))
samp$c_ln_na_bio1[samp$solnas == F] <- NA
samp$c_ln_na_bio1[samp$solnas == T] <- data$c_ln_na_bio1[samp$solnas == T]


samp$sex <- ifelse(samp$sex == "M", 1, 0)
samp$hisp.strat <- 1 * samp$hisp.strat
samp$age.strat <- 1 * samp$age.strat
samp$solnas <- 1 * samp$solnas
samp <- samp %>% select(-bkg)
#samp$R <- ifelse(is.na(c_ln_na_bio1), 0, 1)

write.csv(samp, "Missing1.csv")
imp_list2 <- list(0)
for (i in seq(0, 9)){
  curr <- read.csv(paste0("Data//tryMis1One", i, ".csv"), header = F)
  names(curr) <- names(samp)
  curr$BGid <- data$BGid
  curr$strat <- data$strat
  curr$bghhsub_s2 <- data$bghhsub_s2
  imp_list2[[i + 1]] <- curr
}

samp$BGid <- data$BGid
samp$strat <- data$strat
samp$bghhsub_s2 <- data$bghhsub_s2
save(imp_list2, file = "imp_list2.RData")

imp_list <- imp_list2

source("gain_torch_modified_1.R")
imp_list <- list(0)
for (i in 1:10){
  
  imp_list[[i]] <- gain(samp, n = 1000)
  
}
load("imp_list2.RData")

modcoef_hyper1 <- modvar_hyper1 <- modcoef_sbp1 <- modvar_sbp1 <- matrix(rep(0, 9 * 10), ncol = 9)
for (i in 1:10){
  
  mi.design <- svydesign(id=~BGid, strata=~strat, weights=~bghhsub_s2, data=imp_list[[i]])
  
  mod_hyper <- svyglm(hypertension ~ c_age + c_bmi + c_ln_na_bio1 + 
                        high_chol + usborn + female + bkg_pr + bkg_o,design=mi.design,family=quasibinomial())
  mod_sbp <- svyglm(sbp ~ c_age + c_bmi + c_ln_na_bio1 + 
                      high_chol + usborn + female + bkg_pr + bkg_o,design=mi.design,family=gaussian())
  
  modcoef_hyper1[i, ] <- mod_hyper$coeff
  modcoef_sbp1[i, ] <- mod_sbp$coeff
  
  modvar_hyper1[i, ] <- summary(mod_hyper)$coeff[, 2]^2
  modvar_sbp1[i, ] <- summary(mod_sbp)$coeff[, 2]^2
}


full_design <- svydesign(id=~BGid, strata=~strat, weights=~bghhsub_s2, data=data)
mod_full_hyper <- svyglm(hypertension ~ c_age + c_bmi + c_ln_na_bio1 + 
                        high_chol + usborn + female + 
                          bkg_pr + bkg_o,design=full_design,family=quasibinomial())
mod_full_sbp <- svyglm(sbp ~ c_age + c_bmi + c_ln_na_bio1 + 
                      high_chol + usborn + female + bkg_pr + bkg_o,design=full_design,family=gaussian())

coef(mod_full_hyper)
modcoef_hyper
modcoef_hyper1
coef(mod_full_sbp)
modcoef_sbp
modcoef_sbp1

modvar_hyper
modvar_sbp
diag(vcov(mod_full_hyper))
diag(vcov(mod_full_sbp))
```

